#http://localhost:8080/h2-console
logging.level.root: debug

spring:
  data:
    jpa:
      repositories:
        bootstrap-mode: default
        enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true

