debug: true

spring:
  application:
    name: api-gateway-service
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        hbm2ddl.auto: none
  mvc:
    converters:
      preferred-json-mapper: jackson

#  security:
#    filter:
#      order: 10